apiVersion: v1
kind: Namespace
metadata:
  name: shutdown-demo
  labels:
    app.kubernetes.io/name: shutdown-demo
    app.kubernetes.io/part-of: shutdown-demo
    pod-security.kubernetes.io/enforce: restricted
